name: Testing stuff

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: commit messages 1
        env:
          COMMIT_MESSAGES_1: ${{ join(toJson(github.event.commits.*.message)) }}
        run: echo "$COMMIT_MESSAGES_1"
      - name: commit messages 2 the right
        env:
          COMMIT_MESSAGES_2: ${{ contains(join(toJson(github.event.commits.*.message), ', '), '#skip') }}
        run: echo "$COMMIT_MESSAGES_2"
      - name: commit messages 3
        env:
          COMMIT_MESSAGES_3: ${{ !contains(github.event.commits.*.message, '#skip') }}
        run: echo "$COMMIT_MESSAGES_3"
      - name: commit messages 4 test
        env:
          COMMIT_MESSAGES_4: ${{ (join(toJson(github.event.commits.*.message), ', ')) }}
        run: echo "$COMMIT_MESSAGES_4"
